# Pharmagen - Pharmacogenetic Prediction and Therapeutic Efficacy
# Copyright (C) 2025 Adrim Hamed Outmani
# Licensed under the GNU GPLv3. See LICENSE file in the project root.
#
# src/config/config.toml
[metadata]
project_name = "Pharmagen"
version = "0.7"
author = "Adrim Hamed Outmani"

[project]
multi_label_cols = ["phenotype_outcome"]
seed = 711

[hyperparameters]
# Valores por defecto para cualquier modelo si no se especifican
embedding_dim = 128
n_layers = 2
hidden_dim = 2048
dropout_rate = 0.2
weight_decay = 1e-3
learning_rate = 1e-4
batch_size = 128
optimizer_type = "adamw"
activation_function = "gelu"
use_batch_norm = false
use_layer_norm = false
early_stopping_patience = 15
scheduler_type = "plateau"

# Parámetros específicos de arquitecturas complejas (Defaults)
attention_dim_feedforward = 512
attention_dropout = 0.1
num_attention_layers = 1
fm_dropout = 0.1
fm_hidden_layers = 0
fm_hidden_dim = 256
